name: Publish to Open-VSX

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Extension
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Compile TypeScript
        run: npm run compile

  package:
    needs: test
    runs-on: ubuntu-latest
    name: Package Extension
    outputs:
      vsix-path: ${{ steps.package.outputs.vsix-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        id: package
        run: |
          vsce package
          echo "vsix-path=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: '*.vsix'

  publish-openvsx:
    needs: [test, package]
    runs-on: ubuntu-latest
    name: Publish to Open-VSX
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package

      - name: Install ovsx
        run: npm install -g ovsx

      - name: Publish to Open-VSX
        run: |
          vsix_file=$(ls *.vsix)
          ovsx publish $vsix_file -p ${{ secrets.OPEN_VSX_TOKEN }}
        env:
          OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
